### ISSUE TITLE
Breakpoint not valid if the page is not in hidden overflow

### ISSUE THREAD

**Issue by jdacosta** [wide/breakpoint#1]
Example in mobile: 

Mobile: 320px width
Div block : 1200px width (no overflow hidden)

The breakpoint returned is incorrect. This is due to the `window.innerWith` which should probably be replaced by `window.outerWith`

**Comment by robiseb** [comment]
Hi @jdacosta,

We should use `window.visualViewport.width` which give you what you're looking for.  
Note that **it is not** supported by Internet Explorer ([https://caniuse.com/mdn-api_visualviewport_width](https://caniuse.com/mdn-api_visualviewport_width)).

Be careful using `window.outerWith`, it could gives you wrong values due to toolbar (like Opera for example, it has a left toolbar which its width is added in `window.outerWith`).

I make the changes.

Thanks
